AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tweet-sentiment

  Performs tweet sentiment analysis, logs sentiment scores to CW Metrics

Resources:
  TweetSentiment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/TweetSentiment-1.0.2.jar
      Handler: com.amazonaws.serverless.tweetsentiment.lambda.TweetSentimentHandler::handleRequest
      Runtime: java8
      MemorySize: 768
      Timeout: 60
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - CloudWatchPutMetricPolicy: {}

Outputs:
  TweetSentimentFunction:
    Description: "TweetSentiment Lambda Function ARN"
    Value: !GetAtt TweetSentiment.Arn
